---
# tasks file for kubeadm

# Update APT
- name: APT update
    apt:
        update_cache: yes
        autoclean: yes
        autoremove: yes

# https://docs.docker.com/install/linux/docker-ce/ubuntu/
- name: Add Docker’s official GPG key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    args:
        warn: no

- name: Setup Docker's stable repository
    shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: APT update
    apt:
        update_cache: yes

- name: Install docker-ce & containerd.io
    shell: apt-get install -y docker-ce containerd.io

- name: Hold version of kubelet, kubeadm and kubectl
    shell: apt-mark hold -y docker-ce containerd.io

# https://kubernetes.io/docs/setup/independent/install-kubeadm/
- name: Add Google Cloud Repo Key
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  args:
    warn: no

- name: Setup Docker's stable repository
    shell: sudo add-apt-repository "deb https://apt.kubernetes.io/ kubernetes-xenial main"

- name: APT Update
    apt:
        update_cache: yes

- name: Install kubelet, kubeadm and kubectl
    shell: apt-get install -y kubelet kubeadm kubectl

- name: Hold version of kubelet, kubeadm and kubectl
    shell: apt-mark hold -y kubelet kubeadm kubectl
