---
- name: apt-get update
    apt:
        update_cache: yes
        autoclean: yes
        autoremove: yes

- name: apt-get upgrade
    apt:
        upgrade: full

- name: Add dependencies
    shell: apt-get install -y python-apt apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    args:
        warn: no

- name: Reboot
    shell: sleep 2 && shutdown -r now "Ansible Reboot"
    async: 1
    poll: 0
    ignore_errors: True
    when: cmdline or timezone or hostname is changed

- name: Wait for Reboot
    local_action: wait_for
    args:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 15
        timeout: 120
    become: False

- name: apt-get autoclean & autoremove
    apt:
        autoclean: yes
        autoremove: yes
